---
- name: deploying yaml file
  hosts: tomcat
  become: yes
  tasks:
  - name: deploy files
    copy:
      src: '{{ item }}'
      dest: /var/lib/tomcat/webapps
    with_fileglob: "target/hello-*.war"